Refer to this post, which explains the issue showing here:

[Create 3D array using Python](https://stackoverflow.com/questions/10668341/create-3d-array-using-python)

You could have produced a data structure with a statement that looked like the one you tried, but it would have had side effects since the inner lists are copy-by-reference:

## Use List Comprehension

In [31]:
import pprint
n = 3
d3_array = [[[0 for k in range(n)] for j in range(n)] for i in range(n)]
d2_array = [[0 for j in range(n)] for i in range(n)]
d1_array = [0 for i in range(n)]
pprint.pprint(d1_array)
pprint.pprint(d2_array)
pprint.pprint(d3_array)

[0, 0, 0]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]


## Use Numpy

In [39]:
import numpy as np
pprint.pprint(np.zeros(3))
pprint.pprint(np.zeros((3,3)))
pprint.pprint(np.zeros((3,3,3)))

array([0., 0., 0.])
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])


In [1]:
# create 5 identical copies of itself
ls1 = [[0,0,0]]*5

In [2]:
ls1

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [3]:
hex(id(ls1[0])), hex(id(ls1[0][0])) 

('0x7f80184ecf80', '0x10b07d9f0')

In [4]:
hex(id(ls1[1])),hex(id(ls1[1][0]))

('0x7f80184ecf80', '0x10b07d9f0')

In [5]:
ls1[0][0] = 1
ls1

[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]]

In [6]:
hex(id(ls1[0])), hex(id(ls1[0][0])) 

('0x7f80184ecf80', '0x10b07da10')

In [7]:
hex(id(ls1[1])),hex(id(ls1[1][0]))

('0x7f80184ecf80', '0x10b07da10')

In [8]:
# use list comprehension
ls2 = [[0,0,0] for i in range(5)]

In [9]:
ls2

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [10]:
hex(id(ls2[0])), hex(id(ls2[0][0])) 

('0x7f80184f1540', '0x10b07d9f0')

In [11]:
hex(id(ls2[1])),hex(id(ls2[1][0]))

('0x7f80184f1300', '0x10b07d9f0')

In [12]:
ls2[0][0] = 1
ls2

[[1, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [13]:
hex(id(ls2[0])), hex(id(ls2[0][0])) 

('0x7f80184f1540', '0x10b07da10')

In [14]:
hex(id(ls2[1])),hex(id(ls2[1][0]))

('0x7f80184f1300', '0x10b07d9f0')

In [15]:
hex(id(ls1[0])) == hex(id(ls1[1]))

True

In [16]:
hex(id(ls2[0])) == hex(id(ls2[1]))

False

In [17]:
ls3 = [0]*5
ls3

[0, 0, 0, 0, 0]

In [18]:
hex(id(ls3[0]))

'0x10b07d9f0'

In [19]:
hex(id(ls3[1]))

'0x10b07d9f0'

In [20]:
hex(id(ls3))

'0x7f80184b49c0'

In [21]:
hex(id(ls3[0])) == hex(id(ls3[1]))

True

In [22]:
ls3[0] = 1
ls3

[1, 0, 0, 0, 0]

In [23]:
hex(id(ls3[0]))

'0x10b07da10'

In [24]:
hex(id(ls3[1]))

'0x10b07d9f0'

In [25]:
hex(id(ls3[0])) == hex(id(ls3[1]))

False